site_name: "frml"
docs_dir: pages
site_dir: docs

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          members_order: source
          filters: []

markdown_extensions:
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- markdown_include.include:
    base_path: docs

exclude_docs: >
  *~
